/**
 * MOCK DATA ONLY - replace with real API later
 */
import type { Monitor, MonitorCheck } from '@/lib/types';

const now = Date.now();
const mins = (n: number) => new Date(now - n * 60_000).toISOString();

export const initialMonitors: Monitor[] = [
  {
    id: 'mon-001',
    name: 'Production API',
    description: 'Primary REST API health endpoint',
    type: 'HTTPS',
    target: 'https://api.acme.com/health',
    status: 'UP',
    tags: ['api', 'critical'],
    group: 'Production',
    checkInterval: 60,
    timeout: 30,
    retryCount: 3,
    isActive: true,
    maintenanceMode: false,
    lastResponseTime: 124,
    lastCheckedAt: mins(1),
    uptimePercent: 99.95,
    createdAt: mins(60 * 24 * 30),
    updatedAt: mins(1),
  },
  {
    id: 'mon-002',
    name: 'Marketing Website',
    description: 'Public marketing site',
    type: 'HTTP',
    target: 'https://www.acme.com',
    status: 'UP',
    tags: ['web'],
    group: 'Production',
    checkInterval: 120,
    timeout: 30,
    retryCount: 2,
    isActive: true,
    maintenanceMode: false,
    lastResponseTime: 89,
    lastCheckedAt: mins(2),
    uptimePercent: 99.99,
    createdAt: mins(60 * 24 * 45),
    updatedAt: mins(2),
  },
  {
    id: 'mon-003',
    name: 'Database Primary',
    type: 'TCP',
    target: 'db-primary.internal:5432',
    status: 'DEGRADED',
    tags: ['database', 'critical'],
    group: 'Infrastructure',
    checkInterval: 60,
    timeout: 15,
    retryCount: 3,
    isActive: true,
    maintenanceMode: false,
    lastResponseTime: 890,
    lastCheckedAt: mins(1),
    uptimePercent: 98.2,
    createdAt: mins(60 * 24 * 60),
    updatedAt: mins(1),
  },
  {
    id: 'mon-004',
    name: 'VPN Gateway',
    type: 'PING',
    target: '10.0.1.1',
    status: 'DOWN',
    tags: ['network'],
    group: 'Infrastructure',
    checkInterval: 60,
    timeout: 10,
    retryCount: 3,
    isActive: true,
    maintenanceMode: false,
    lastResponseTime: null,
    lastCheckedAt: mins(3),
    uptimePercent: 97.5,
    createdAt: mins(60 * 24 * 20),
    updatedAt: mins(3),
  },
  {
    id: 'mon-005',
    name: 'CDN Edge',
    type: 'HTTPS',
    target: 'https://cdn.acme.com',
    status: 'UP',
    tags: ['cdn'],
    group: 'Production',
    checkInterval: 300,
    timeout: 30,
    retryCount: 2,
    isActive: true,
    maintenanceMode: false,
    lastResponseTime: 45,
    lastCheckedAt: mins(5),
    uptimePercent: 99.9,
    createdAt: mins(60 * 24 * 15),
    updatedAt: mins(5),
  },
  {
    id: 'mon-006',
    name: 'Mail Server',
    type: 'TCP',
    target: 'mail.acme.com:587',
    status: 'UP',
    tags: ['mail'],
    group: 'Infrastructure',
    checkInterval: 300,
    timeout: 20,
    retryCount: 2,
    isActive: true,
    maintenanceMode: false,
    lastResponseTime: 210,
    lastCheckedAt: mins(4),
    uptimePercent: 99.7,
    createdAt: mins(60 * 24 * 90),
    updatedAt: mins(4),
  },
  {
    id: 'mon-007',
    name: 'SSL Certificate',
    type: 'SSL',
    target: 'api.acme.com',
    status: 'UP',
    tags: ['security'],
    group: 'Security',
    checkInterval: 86400,
    timeout: 30,
    retryCount: 1,
    isActive: true,
    maintenanceMode: false,
    lastResponseTime: 320,
    lastCheckedAt: mins(60),
    uptimePercent: 100,
    createdAt: mins(60 * 24 * 10),
    updatedAt: mins(60),
  },
  {
    id: 'mon-008',
    name: 'DNS Resolver',
    type: 'DNS',
    target: 'acme.com',
    status: 'UP',
    tags: ['dns'],
    group: 'Infrastructure',
    checkInterval: 300,
    timeout: 10,
    retryCount: 2,
    isActive: false,
    maintenanceMode: false,
    lastResponseTime: 18,
    lastCheckedAt: mins(120),
    uptimePercent: 99.5,
    createdAt: mins(60 * 24 * 25),
    updatedAt: mins(120),
  },
];

export const initialMonitorChecks: Record<string, MonitorCheck[]> = {
  'mon-001': [
    { id: 'chk-001-1', status: 'UP', responseTime: 124, createdAt: mins(1) },
    { id: 'chk-001-2', status: 'UP', responseTime: 118, createdAt: mins(2) },
    { id: 'chk-001-3', status: 'UP', responseTime: 131, createdAt: mins(3) },
    { id: 'chk-001-4', status: 'DEGRADED', responseTime: 456, createdAt: mins(4) },
    { id: 'chk-001-5', status: 'UP', responseTime: 122, createdAt: mins(5) },
  ],
  'mon-002': [
    { id: 'chk-002-1', status: 'UP', responseTime: 89, createdAt: mins(2) },
    { id: 'chk-002-2', status: 'UP', responseTime: 92, createdAt: mins(4) },
    { id: 'chk-002-3', status: 'UP', responseTime: 85, createdAt: mins(6) },
  ],
  'mon-003': [
    { id: 'chk-003-1', status: 'DEGRADED', responseTime: 890, createdAt: mins(1) },
    { id: 'chk-003-2', status: 'DEGRADED', responseTime: 820, createdAt: mins(2) },
    { id: 'chk-003-3', status: 'UP', responseTime: 145, createdAt: mins(3) },
  ],
  'mon-004': [
    { id: 'chk-004-1', status: 'DOWN', responseTime: null, errorMessage: 'Request timeout', createdAt: mins(3) },
    { id: 'chk-004-2', status: 'DOWN', responseTime: null, errorMessage: 'Host unreachable', createdAt: mins(4) },
    { id: 'chk-004-3', status: 'UP', responseTime: 12, createdAt: mins(5) },
  ],
  'mon-005': [
    { id: 'chk-005-1', status: 'UP', responseTime: 45, createdAt: mins(5) },
    { id: 'chk-005-2', status: 'UP', responseTime: 48, createdAt: mins(10) },
  ],
};

export const initialMonitorAlertHistory: Record<
  string,
  { id: string; trigger: string; status: string; createdAt: string }[]
> = {
  'mon-001': [
    { id: 'al-001', trigger: 'HIGH_LATENCY', status: 'SENT', createdAt: mins(30) },
    { id: 'al-002', trigger: 'MONITOR_RECOVERY', status: 'SENT', createdAt: mins(60) },
  ],
  'mon-003': [
    { id: 'al-003', trigger: 'HIGH_LATENCY', status: 'SENT', createdAt: mins(15) },
  ],
  'mon-004': [
    { id: 'al-004', trigger: 'MONITOR_DOWN', status: 'SENT', createdAt: mins(3) },
    { id: 'al-005', trigger: 'MONITOR_DOWN', status: 'FAILED', createdAt: mins(10) },
  ],
};
