export enum AlertTrigger {
  MONITOR_DOWN = 'MONITOR_DOWN',
  MONITOR_RECOVERY = 'MONITOR_RECOVERY',
  HIGH_LATENCY = 'HIGH_LATENCY',
  PACKET_LOSS = 'PACKET_LOSS',
  SSL_EXPIRY = 'SSL_EXPIRY',
  DNS_FAILURE = 'DNS_FAILURE',
}
